# Generated by Django 5.0.4 on 2024-05-29 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=200)),
                ('des', models.TextField()),
                ('content', models.TextField()),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('modifica', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
