# Generated by Django 5.0.3 on 2024-03-28 00:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsuariosEspecialistas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos/', verbose_name='Foto para tu perfil')),
                ('descripcion', models.CharField(max_length=250)),
                ('estado_suscripcion', models.PositiveSmallIntegerField(choices=[(0, 'Bloqueado'), (1, 'Vigente')])),
                ('promedio_evaluacion', models.DecimalField(decimal_places=2, max_digits=4)),
                ('tiempo_consulta', models.PositiveSmallIntegerField()),
                ('reg_especialista', models.CharField(max_length=120)),
                ('ctr_altadctos', models.PositiveSmallIntegerField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablas.categorias')),
                ('rubro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablas.rubros')),
                ('subcategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablas.subcategorias')),
            ],
            options={
                'db_table': 'usuarios_especialistas',
                'ordering': ['foto', 'descripcion', 'estado_suscripcion', 'promedio_evaluacion', 'tiempo_consulta', 'reg_especialista', 'ctr_altadctos', 'categoria', 'subcategoria', 'rubro', 'usuario'],
            },
        ),
        migrations.CreateModel(
            name='UsuariosPersonas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=20)),
                ('dv', models.CharField(max_length=1)),
                ('estado', models.PositiveSmallIntegerField(choices=[(0, 'Bloqueado'), (1, 'Habilitado'), (2, 'En Proceso'), (3, 'En Revision')])),
                ('fnacimiento', models.DateField()),
                ('telefono', models.CharField(max_length=20)),
                ('ciudad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tablas.ciudades')),
                ('comuna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tablas.comunas')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tablas.regiones')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usuarios_personas',
            },
        ),
        migrations.CreateModel(
            name='UsuariosEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('mensaje', models.CharField(max_length=120)),
                ('evaluacion', models.PositiveSmallIntegerField()),
                ('especialista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuariosespecialistas')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuariospersonas')),
            ],
            options={
                'db_table': 'usuarios_evaluaciones',
                'ordering': ['fecha', 'mensaje', 'evaluacion', 'usuario', 'especialista'],
            },
        ),
        migrations.AddField(
            model_name='usuariosespecialistas',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuariospersonas'),
        ),
    ]
