# Generated by Django 5.0.3 on 2024-04-04 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariosespecialistas',
            name='estado_suscripcion',
            field=models.CharField(choices=[('0', 'Bloqueado'), ('1', 'Vigente')], max_length=1),
        ),
        migrations.AlterField(
            model_name='usuariospersonas',
            name='estado',
            field=models.CharField(choices=[('0', 'Bloqueado'), ('1', 'Habilitado'), ('2', 'En Proceso'), ('3', 'En Revision')], max_length=1),
        ),
    ]
