# Generated by Django 5.0.3 on 2024-05-25 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariosespecialistas',
            name='promedio_evaluacion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
