# Generated by Django 5.0.3 on 2024-04-10 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuariosespecialistas_estado_suscripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariospersonas',
            name='perfil',
            field=models.CharField(choices=[('0', 'root'), ('1', 'Administrador'), ('2', 'Especialista'), ('3', 'Registrado'), ('4', 'Invitado'), ('5', 'Relacionado')], default=5, max_length=1),
            preserve_default=False,
        ),
    ]
