# Generated by Django 5.0.3 on 2024-05-28 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuariosespecialistas_promedio_evaluacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuariosespecialistas',
            options={'ordering': ['foto', 'descripcion', 'estado_suscripcion', 'promedio_evaluacion', 'tiempo_consulta', 'reg_especialista', 'ctr_altadctos', 'categoria', 'subcategoria', 'rubro', 'persona', 'plan']},
        ),
        migrations.RemoveField(
            model_name='usuariosespecialistas',
            name='upload_to',
        ),
    ]
