# Generated by Django 5.0.3 on 2024-06-11 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuariosespecialistas_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuariosRegisterRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fregistro', models.DateField(auto_now_add=True)),
                ('rut', models.CharField(max_length=45)),
                ('nombre', models.CharField(max_length=150)),
                ('apellido', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=20)),
                ('token', models.CharField(max_length=64)),
                ('perfil', models.CharField(choices=[('0', 'root'), ('1', 'Administrador'), ('2', 'Especialista'), ('3', 'Registrado'), ('4', 'Invitado'), ('5', 'Relacionado')], default='3', max_length=1)),
            ],
            options={
                'db_table': 'usuarios_registros',
                'ordering': ['fregistro', 'rut', 'nombre', 'apellido', 'email', 'telefono', 'token', 'perfil'],
            },
        ),
    ]
