# Generated by Django 5.0.3 on 2024-04-12 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuariospersonas_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariospersonas',
            name='dv',
        ),
    ]
