# Generated by Django 5.0.3 on 2024-04-22 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablas', '0006_alter_categorias_options_alter_ciudades_options_and_more'),
        ('usuarios', '0004_remove_usuariospersonas_dv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariosespecialistas',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tablas.categorias'),
        ),
        migrations.AlterField(
            model_name='usuariosespecialistas',
            name='rubro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tablas.rubros'),
        ),
        migrations.AlterField(
            model_name='usuariosespecialistas',
            name='subcategoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tablas.subcategorias'),
        ),
    ]
