# Generated by Django 5.0.3 on 2024-06-13 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_usuariosregisterrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariospersonas',
            name='perfil',
            field=models.CharField(choices=[(0, 'root'), (1, 'Administrador'), (2, 'Especialista'), (3, 'Registrado'), (4, 'Invitado'), (5, 'Relacionado')], default=3, max_length=1),
        ),
        migrations.AlterField(
            model_name='usuariosregisterrequest',
            name='perfil',
            field=models.CharField(choices=[(0, 'root'), (1, 'Administrador'), (2, 'Especialista'), (3, 'Registrado'), (4, 'Invitado'), (5, 'Relacionado')], default=3, max_length=1),
        ),
    ]
