# Generated by Django 5.0.3 on 2024-04-24 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_usuariosespecialistas_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariosespecialistas',
            name='ctr_altadctos',
            field=models.CharField(choices=[('0', 'Pendientes'), ('1', 'Vigentes')], max_length=1),
        ),
        migrations.AlterField(
            model_name='usuariosespecialistas',
            name='estado_suscripcion',
            field=models.CharField(choices=[('0', 'Bloqueada'), ('1', 'Vigente')], max_length=1),
        ),
    ]
