# Generated by Django 5.0.3 on 2024-06-13 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_usuariospersonas_perfil_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuariosregisterrequest',
            options={'ordering': ['fregistro', 'rut', 'nombre', 'apellido', 'email', 'telefono', 'token', 'perfil', 'plan', 'fpago']},
        ),
        migrations.AddField(
            model_name='usuariosregisterrequest',
            name='fpago',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='usuariosregisterrequest',
            name='plan',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
