# Generated by Django 5.0.3 on 2024-06-16 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_usuariosregisterrequest_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuariosregisterrequest',
            options={'ordering': ['fregistro', 'rut', 'nombre', 'apellido', 'email', 'telefono', 'fnacimiento', 'token', 'perfil', 'plan', 'fpago']},
        ),
        migrations.AddField(
            model_name='usuariosregisterrequest',
            name='fnacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
