# Generated by Django 5.0.3 on 2024-04-25 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_usuariosespecialistas_ctr_altadctos_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuariosespecialistas',
            options={'ordering': ['foto', 'descripcion', 'estado_suscripcion', 'promedio_evaluacion', 'tiempo_consulta', 'reg_especialista', 'ctr_altadctos', 'categoria', 'subcategoria', 'rubro', 'persona']},
        ),
        migrations.RenameField(
            model_name='usuariosespecialistas',
            old_name='usuario',
            new_name='persona',
        ),
        migrations.AlterField(
            model_name='usuariosespecialistas',
            name='ctr_altadctos',
            field=models.CharField(choices=[('0', 'Pendiente'), ('1', 'Revisado')], max_length=1),
        ),
    ]
