# Generated by Django 5.0.3 on 2024-04-26 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_usuariosespecialistas_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariosespecialistas',
            name='promedio_evaluacion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
