# Generated by Django 5.0.3 on 2024-06-26 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_alter_usuariosregisterrequest_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariosespecialistas',
            name='tiempo_consulta',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usuariosregisterrequest',
            name='solicita',
            field=models.CharField(choices=[('0', 'Usuario'), ('1', 'Suscriptor'), ('2', 'Clave')], default='0', max_length=1),
        ),
    ]
