# Generated by Django 5.0.3 on 2024-05-13 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_alter_usuariosespecialistas_promedio_evaluacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariosespecialistas',
            name='ctr_altadctos',
            field=models.CharField(choices=[('0', 'Pendiente'), ('1', 'Revisados')], max_length=1),
        ),
    ]
