# Generated by Django 5.0.3 on 2024-07-01 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especialistas', '0020_alter_especialistaspagos_options'),
        ('usuarios', '0009_alter_usuariosespecialistas_tiempo_consulta_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuariosregisterrequest',
            options={'ordering': ['fregistro', 'rut', 'nombre', 'apellido', 'email', 'telefono', 'fnacimiento', 'token', 'solicita', 'plan', 'fpago', 'pago']},
        ),
        migrations.AddField(
            model_name='usuariosregisterrequest',
            name='pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='especialistas.especialistaspagos'),
        ),
        migrations.AlterField(
            model_name='usuariospersonas',
            name='perfil',
            field=models.CharField(choices=[('0', 'root'), ('1', 'Administrador'), ('2', 'Especialista'), ('3', 'Registrado'), ('4', 'Invitado'), ('5', 'Relacionado')], default='3', max_length=1),
        ),
        migrations.AlterField(
            model_name='usuariosregisterrequest',
            name='solicita',
            field=models.CharField(choices=[('0', 'Usuario'), ('1', 'Suscriptor'), ('2', 'Revisar Pago')], default='0', max_length=1),
        ),
    ]
