# Generated by Django 5.0.3 on 2024-07-01 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_alter_usuariosregisterrequest_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuariosregisterrequest',
            options={'ordering': ['fregistro', 'rut', 'nombre', 'apellido', 'email', 'telefono', 'fnacimiento', 'token', 'solicita', 'plan', 'fpago']},
        ),
        migrations.RemoveField(
            model_name='usuariosregisterrequest',
            name='pago',
        ),
    ]
