# Generated by Django 5.0.3 on 2024-07-01 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especialistas', '0020_alter_especialistaspagos_options'),
        ('usuarios', '0011_alter_usuariosregisterrequest_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuariosregisterrequest',
            options={'ordering': ['fregistro', 'rut', 'nombre', 'apellido', 'email', 'telefono', 'fnacimiento', 'token', 'solicita', 'plan', 'fpago', 'epago']},
        ),
        migrations.AddField(
            model_name='usuariosregisterrequest',
            name='epago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='especialistas.especialistaspagos'),
        ),
    ]
