# Generated by Django 5.0.3 on 2024-07-01 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_alter_usuariosregisterrequest_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuariosregisterrequest',
            options={},
        ),
    ]
