# Generated by Django 5.0.3 on 2024-07-05 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_alter_usuariosregisterrequest_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuariospersonas',
            options={'ordering': ['rut', 'estado', 'perfil', 'fnacimiento', 'telefono', 'cclave', 'region', 'comuna', 'ciudad', 'usuario']},
        ),
        migrations.AddField(
            model_name='usuariospersonas',
            name='cclave',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
