# Generated by Django 5.0.3 on 2024-03-28 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EspecialistaAgendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.CharField(max_length=5)),
                ('hora_termino', models.CharField(max_length=5)),
                ('estado', models.PositiveSmallIntegerField(choices=[(0, 'Agendada'), (1, 'Disponible')])),
            ],
            options={
                'db_table': 'especialistas_agendas',
                'ordering': ['fecha', 'hora_inicio', 'hora_termino', 'estado', 'esp_consultas', 'especialista'],
            },
        ),
        migrations.CreateModel(
            name='EspecialistaFichas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('archivo_dcto', models.CharField(max_length=45)),
                ('observaciones', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'especialistas_fichas',
                'ordering': ['fecha', 'archivo_dcto', 'observaciones', 'especialista', 'usuario'],
            },
        ),
        migrations.CreateModel(
            name='EspecialistasConsultas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fdesde', models.DateField()),
                ('fhasta', models.DateField()),
                ('direccion', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'especialistas_consultas',
                'ordering': ['fdesde', 'fhasta', 'direccion', 'ciudad', 'especialista'],
            },
        ),
        migrations.CreateModel(
            name='EspecialistasContratos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_replegal', models.CharField(max_length=20)),
                ('nombre_replegal', models.CharField(max_length=120)),
                ('direccion', models.CharField(max_length=250)),
                ('fono', models.CharField(max_length=20)),
                ('ctr_pagos', models.PositiveSmallIntegerField(choices=[(0, 'Atrasado'), (1, 'Al Dia')])),
                ('finicio', models.DateField()),
                ('ftermino', models.DateField()),
                ('monto_contrato', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'especialistas_contratos',
                'ordering': ['rut_replegal', 'nombre_replegal', 'direccion', 'fono', 'ctr_pagos', 'finicio', 'ftermino', 'monto_contrato', 'region', 'comuna', 'ciudad', 'especialista', 'promocion', 'plansuscripcion'],
            },
        ),
        migrations.CreateModel(
            name='EspecialistasHorasAgendadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.CharField(max_length=5)),
                ('mensaje', models.CharField(max_length=120)),
                ('relacionado', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'especialistas_horasagendadas',
                'ordering': ['fecha', 'hora', 'mensaje', 'usuario', 'relacionado', 'esp_agenda', 'especialista'],
            },
        ),
        migrations.CreateModel(
            name='EspecialistasPagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fdesde', models.DateField()),
                ('fhasta', models.DateField()),
                ('estado', models.PositiveSmallIntegerField(choices=[(0, 'Pendiente'), (1, 'Pagado')])),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('numero_pago', models.CharField(max_length=120)),
                ('fpago', models.DateField()),
            ],
            options={
                'db_table': 'especialistas_pagos',
                'ordering': ['fdesde', 'fhasta', 'estado', 'numero_pago', 'fpago', 'formapago', 'plansuscripcion', 'contrato', 'especialista'],
            },
        ),
        migrations.CreateModel(
            name='EspecialistasPlanesSuscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fdesde', models.DateField()),
                ('fhasta', models.DateField()),
                ('nombre', models.CharField(max_length=45)),
                ('estado', models.PositiveSmallIntegerField(choices=[(0, 'Terminado'), (1, 'Vigente')])),
                ('periodicidad', models.PositiveIntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'especialistas_planessucripcion',
                'ordering': ['fdesde', 'fhasta', 'nombre', 'estado', 'periodicidad', 'valor'],
            },
        ),
        migrations.CreateModel(
            name='EspecialistasRubroSaludPagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_atencion', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.CharField(max_length=120)),
            ],
            options={
                'db_table': 'especialistas_rsaludpagos',
                'ordering': ['valor_atencion', 'descripcion', 'formapagosalud', 'prevision', 'modatencion', 'rubro', 'especialista'],
            },
        ),
    ]
