# Generated by Django 5.0.3 on 2024-05-22 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tablas', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EspecialistasPlanesSuscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fdesde', models.DateField()),
                ('fhasta', models.DateField()),
                ('nombre', models.CharField(max_length=45)),
                ('estado', models.CharField(choices=[('0', 'Terminado'), ('1', 'Vigente')], max_length=1)),
                ('periodicidad', models.PositiveIntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'especialistas_planessucripcion',
                'ordering': ['fdesde', 'fhasta', 'nombre', 'estado', 'periodicidad', 'valor'],
            },
        ),
        migrations.CreateModel(
            name='EspecialistasConsultas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fdesde', models.DateField()),
                ('fhasta', models.DateField()),
                ('direccion', models.CharField(max_length=250)),
                ('estado', models.CharField(choices=[('0', 'Terminada'), ('1', 'Disponible')], default='1', max_length=1)),
                ('ciudad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consulta_ciudad', to='tablas.ciudades')),
                ('especialista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consulta_especialista', to='usuarios.usuariosespecialistas')),
            ],
            options={
                'db_table': 'especialistas_consultas',
                'ordering': ['fdesde', 'fhasta', 'direccion', 'estado', 'ciudad', 'especialista'],
            },
        ),
        migrations.CreateModel(
            name='EspecialistasAgendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hinicio', models.DateField()),
                ('htermino', models.DateField()),
                ('estado', models.CharField(choices=[('0', 'Anulada'), ('1', 'Disponible'), ('2', 'Agendada')], default='1', max_length=1)),
                ('especialista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuariosespecialistas')),
                ('consulta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='especialistas.especialistasconsultas')),
            ],
            options={
                'db_table': 'especialistas_programas',
                'ordering': ['fecha', 'hinicio', 'htermino', 'estado', 'consulta', 'especialista'],
            },
        ),
        migrations.CreateModel(
            name='EspecialistasContratos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_replegal', models.CharField(max_length=20)),
                ('nombre_replegal', models.CharField(max_length=120)),
                ('direccion', models.CharField(max_length=120)),
                ('fono', models.CharField(max_length=20)),
                ('estado', models.CharField(choices=[('0', 'Atrasado'), ('1', 'Al Dia')], default='0', max_length=1)),
                ('finicio', models.DateField()),
                ('ftermino', models.DateField()),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ciudad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contrato_ciudad', to='tablas.ciudades')),
                ('comuna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contrato_comuna', to='tablas.comunas')),
                ('especialista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrato_especialista', to='usuarios.usuariosespecialistas')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contrato_plan', to='tablas.planes')),
                ('promocion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contrato_promocion', to='tablas.promociones')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contrato_region', to='tablas.regiones')),
            ],
            options={
                'db_table': 'especialistas_contratos',
                'ordering': ['rut_replegal', 'nombre_replegal', 'direccion', 'fono', 'estado', 'finicio', 'ftermino', 'valor', 'region', 'comuna', 'ciudad', 'especialista', 'promocion', 'plan'],
            },
        ),
        migrations.CreateModel(
            name='EspecialistasFichas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('archivo', models.FileField(max_length=250, upload_to='')),
                ('observaciones', models.CharField(max_length=250)),
                ('especialista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuariosespecialistas')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuariospersonas')),
            ],
            options={
                'db_table': 'especialistas_fichas',
                'ordering': ['fecha', 'archivo', 'observaciones', 'especialista', 'usuario'],
            },
        ),
        migrations.CreateModel(
            name='EspecialistasHorasAgendadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.CharField(max_length=5)),
                ('mensaje', models.CharField(max_length=120)),
                ('relacionado', models.BigIntegerField(default=0)),
                ('esp_agenda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='especialistas.especialistasagendas')),
                ('especialista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuariosespecialistas')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuariospersonas')),
            ],
            options={
                'db_table': 'especialistas_horasagendadas',
                'ordering': ['fecha', 'hora', 'mensaje', 'usuario', 'relacionado', 'esp_agenda', 'especialista'],
            },
        ),
        migrations.CreateModel(
            name='EspecialistasPagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fdesde', models.DateField()),
                ('fhasta', models.DateField()),
                ('fpago', models.DateField()),
                ('estado', models.CharField(choices=[('0', 'Atrasado'), ('1', 'Al Dia')], default='0', max_length=1)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('numero_dcto', models.CharField(max_length=120)),
                ('contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_contrato', to='especialistas.especialistascontratos')),
                ('especialista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_especialista', to='usuarios.usuariosespecialistas')),
                ('formapago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_fpago', to='tablas.formapagogral')),
            ],
            options={
                'db_table': 'especialistas_pagos',
                'ordering': ['fdesde', 'fhasta', 'fpago', 'estado', 'monto', 'numero_dcto', 'formapago', 'contrato', 'especialista'],
            },
        ),
        migrations.CreateModel(
            name='EspecialistasRSaludPagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bono', models.CharField(max_length=120)),
                ('especialista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuariosespecialistas')),
                ('formapagosalud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tablas.formapagosalud')),
                ('modatencion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tablas.modalidadatencion')),
                ('prevision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tablas.tipoprevision')),
            ],
            options={
                'db_table': 'especialistas_rsaludpagos',
                'ordering': ['valor', 'bono', 'formapagosalud', 'prevision', 'modatencion', 'especialista'],
            },
        ),
        migrations.CreateModel(
            name='UsuariosAgendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingreso', models.DateField(auto_now_add=True)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('mensaje', models.CharField(max_length=250)),
                ('estado', models.CharField(choices=[('0', 'Anulada'), ('1', 'Vigente')], default='1', max_length=1)),
                ('usuariorel', models.PositiveBigIntegerField()),
                ('agendaespecialista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='especialistas.especialistasagendas')),
                ('especialista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuariosespecialistas')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuariospersonas')),
            ],
            options={
                'db_table': 'usuarios_agendas',
                'ordering': ['fingreso', 'fecha', 'hora', 'mensaje', 'estado', 'usuariorel', 'usuario', 'especialista', 'agendaespecialista'],
            },
        ),
    ]
