# Generated by Django 5.0.3 on 2024-03-28 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('especialistas', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='especialistaagendas',
            name='especialista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuariosespecialistas'),
        ),
        migrations.AddField(
            model_name='especialistafichas',
            name='especialista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuariosespecialistas'),
        ),
        migrations.AddField(
            model_name='especialistafichas',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuariospersonas'),
        ),
        migrations.AddField(
            model_name='especialistasconsultas',
            name='ciudad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tablas.ciudades'),
        ),
        migrations.AddField(
            model_name='especialistasconsultas',
            name='especialista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuariosespecialistas'),
        ),
        migrations.AddField(
            model_name='especialistaagendas',
            name='esp_consultas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='especialistas.especialistasconsultas'),
        ),
        migrations.AddField(
            model_name='especialistascontratos',
            name='ciudad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tablas.ciudades'),
        ),
        migrations.AddField(
            model_name='especialistascontratos',
            name='comuna',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tablas.comunas'),
        ),
        migrations.AddField(
            model_name='especialistascontratos',
            name='especialista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuariosespecialistas'),
        ),
        migrations.AddField(
            model_name='especialistascontratos',
            name='promocion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablas.promociones'),
        ),
        migrations.AddField(
            model_name='especialistascontratos',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tablas.regiones'),
        ),
        migrations.AddField(
            model_name='especialistashorasagendadas',
            name='esp_agenda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='especialistas.especialistaagendas'),
        ),
        migrations.AddField(
            model_name='especialistashorasagendadas',
            name='especialista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuariosespecialistas'),
        ),
        migrations.AddField(
            model_name='especialistashorasagendadas',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuariospersonas'),
        ),
        migrations.AddField(
            model_name='especialistaspagos',
            name='contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='especialistas.especialistascontratos'),
        ),
        migrations.AddField(
            model_name='especialistaspagos',
            name='especialista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuariosespecialistas'),
        ),
        migrations.AddField(
            model_name='especialistaspagos',
            name='formapago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tablas.formapagogral'),
        ),
        migrations.AddField(
            model_name='especialistaspagos',
            name='plansuscripcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='especialistas.especialistasplanessuscripcion'),
        ),
        migrations.AddField(
            model_name='especialistascontratos',
            name='plansuscripcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='especialistas.especialistasplanessuscripcion'),
        ),
        migrations.AddField(
            model_name='especialistasrubrosaludpagos',
            name='especialista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuariosespecialistas'),
        ),
        migrations.AddField(
            model_name='especialistasrubrosaludpagos',
            name='formapagosalud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tablas.formapagosalud'),
        ),
        migrations.AddField(
            model_name='especialistasrubrosaludpagos',
            name='modatencion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tablas.modalidadatencion'),
        ),
        migrations.AddField(
            model_name='especialistasrubrosaludpagos',
            name='prevision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tablas.tipoprevision'),
        ),
        migrations.AddField(
            model_name='especialistasrubrosaludpagos',
            name='rubro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablas.rubros'),
        ),
    ]
