# Generated by Django 5.0.3 on 2024-04-02 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especialistas', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialistaagendas',
            name='estado',
            field=models.CharField(choices=[(0, 'Agendada'), (1, 'Disponible')], max_length=1),
        ),
        migrations.AlterField(
            model_name='especialistascontratos',
            name='ctr_pagos',
            field=models.CharField(choices=[(0, 'Atrasado'), (1, 'Al Dia')], max_length=1),
        ),
        migrations.AlterField(
            model_name='especialistaspagos',
            name='estado',
            field=models.CharField(choices=[(0, 'Pendiente'), (1, 'Pagado')], max_length=1),
        ),
        migrations.AlterField(
            model_name='especialistasplanessuscripcion',
            name='estado',
            field=models.CharField(choices=[(0, 'Terminado'), (1, 'Vigente')], max_length=1),
        ),
    ]
