# Generated by Django 5.0.3 on 2024-05-25 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('especialistas', '0003_especialistasdocumentos_especialistasimagenes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='especialistasimagenes',
            name='especialista',
        ),
        migrations.DeleteModel(
            name='EspecialistasDocumentos',
        ),
        migrations.DeleteModel(
            name='EspecialistasImagenes',
        ),
    ]
