# Generated by Django 5.0.3 on 2024-05-25 00:08

import django.db.models.deletion
import proximahora.funciones
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especialistas', '0004_remove_especialistasimagenes_especialista_and_more'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EspecialistasDocumentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('titulo', models.CharField(max_length=120)),
                ('archivo', models.FileField(blank=True, null=True, upload_to=proximahora.funciones.uploaddocu_location)),
                ('upload_to', models.CharField(max_length=120)),
                ('especialista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuariosespecialistas')),
            ],
            options={
                'db_table': 'especialistas_documentos',
                'ordering': ['fecha', 'titulo', 'archivo', 'upload_to', 'especialista'],
            },
        ),
        migrations.CreateModel(
            name='EspecialistasImagenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('titulo', models.CharField(max_length=120)),
                ('archivo', models.ImageField(blank=True, null=True, upload_to=proximahora.funciones.uploaddocu_location)),
                ('upload_to', models.CharField(max_length=120)),
                ('especialista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuariosespecialistas')),
            ],
            options={
                'db_table': 'especialistas_imagenes',
                'ordering': ['fecha', 'titulo', 'archivo', 'upload_to', 'especialista'],
            },
        ),
    ]
