# Generated by Django 5.0.3 on 2024-05-25 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('especialistas', '0005_especialistasdocumentos_especialistasimagenes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EspecialistasImagenes',
        ),
    ]
