# Generated by Django 5.0.3 on 2024-05-25 17:50

import django.db.models.deletion
import proximahora.funciones
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especialistas', '0006_delete_especialistasimagenes'),
        ('usuarios', '0002_alter_usuariosespecialistas_promedio_evaluacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='especialistasdocumentos',
            options={'ordering': ['fecha', 'titulo', 'archivo', 'imagen', 'upload_to', 'especialista', 'usuario']},
        ),

        migrations.AddField(
            model_name='especialistasdocumentos',
            name='usuario',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuariospersonas'),
        ),
    ]
