# Generated by Django 5.0.3 on 2024-05-25 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especialistas', '0007_alter_especialistasdocumentos_options_and_more'),
        ('usuarios', '0002_alter_usuariosespecialistas_promedio_evaluacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialistasdocumentos',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuariospersonas'),
        ),
    ]
