# Generated by Django 5.0.3 on 2024-05-25 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('especialistas', '0008_alter_especialistasdocumentos_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EspecialistasDocumentos',
        ),
    ]
