# Generated by Django 5.0.3 on 2024-05-25 18:03

import django.db.models.deletion
import proximahora.funciones
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especialistas', '0009_delete_especialistasdocumentos'),
        ('usuarios', '0002_alter_usuariosespecialistas_promedio_evaluacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='EspecialistasDocumentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('titulo', models.CharField(max_length=120)),
                ('archivo', models.FileField(blank=True, null=True, upload_to=proximahora.funciones.uploaddocu_location)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=proximahora.funciones.uploaddocu_location)),
                ('upload_to', models.CharField(max_length=120)),
                ('especialista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuariosespecialistas')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuariospersonas')),
            ],
            options={
                'db_table': 'especialistas_documentos',
                'ordering': ['fecha', 'titulo', 'archivo', 'imagen', 'upload_to', 'especialista', 'usuario'],
            },
        ),
    ]
