# Generated by Django 5.0.3 on 2024-05-28 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('especialistas', '0011_alter_especialistasdocumentos_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='especialistasdocumentos',
            options={'ordering': ['fecha', 'titulo', 'archivo', 'especialista', 'usuario']},
        ),
        migrations.RemoveField(
            model_name='especialistasdocumentos',
            name='imagen',
        ),
    ]
