# Generated by Django 5.0.3 on 2024-05-28 22:44

import django.db.models.deletion
import proximahora.funciones
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especialistas', '0012_alter_especialistasdocumentos_options_and_more'),
        ('usuarios', '0003_alter_usuariosespecialistas_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EspecialistasImagenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('titulo', models.CharField(max_length=120)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=proximahora.funciones.uploaddocu_location)),
                ('especialista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuariosespecialistas')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuariospersonas')),
            ],
            options={
                'db_table': 'especialistas_imagenes',
                'ordering': ['fecha', 'titulo', 'imagen', 'especialista', 'usuario'],
            },
        ),
    ]
