# Generated by Django 5.0.3 on 2024-05-29 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('especialistas', '0013_especialistasimagenes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='especialistasdocumentos',
            options={'ordering': ['fecha', 'titulo', 'archivo', 'especialista']},
        ),
        migrations.AlterModelOptions(
            name='especialistasimagenes',
            options={'ordering': ['fecha', 'titulo', 'imagen', 'especialista']},
        ),
        migrations.RemoveField(
            model_name='especialistasdocumentos',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='especialistasimagenes',
            name='usuario',
        ),
    ]
