# Generated by Django 5.0.3 on 2024-06-26 22:11

import proximahora.funciones
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especialistas', '0015_alter_especialistasdocumentos_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='especialistaspagos',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to=proximahora.funciones.uploadpago_location),
        ),
        migrations.AlterField(
            model_name='especialistaspagos',
            name='estado',
            field=models.CharField(choices=[(1, 'Rechazado'), (1, 'Por Confirmar'), (2, 'Confirmado')], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='especialistaspagos',
            name='numero_dcto',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
