# Generated by Django 5.0.3 on 2024-06-27 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('especialistas', '0016_especialistaspagos_documento_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EspecialistasPlanesSuscripcion',
        ),
    ]
