# Generated by Django 5.0.3 on 2024-06-27 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especialistas', '0017_delete_especialistasplanessuscripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialistaspagos',
            name='estado',
            field=models.CharField(choices=[('0', 'Rechazado'), ('1', 'Por Confirmar'), ('2', 'Confirmado')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='especialistaspagos',
            name='fpago',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
