# Generated by Django 5.0.3 on 2024-06-27 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especialistas', '0018_alter_especialistaspagos_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialistaspagos',
            name='fpago',
            field=models.DateField(auto_now=True),
        ),
    ]
