# Generated by Django 5.0.3 on 2024-06-27 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('especialistas', '0019_alter_especialistaspagos_fpago'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='especialistaspagos',
            options={'ordering': ['fdesde', 'fhasta', 'fpago', 'estado', 'monto', 'numero_dcto', 'formapago', 'contrato', 'especialista', 'documento']},
        ),
    ]
