# Generated by Django 5.0.3 on 2024-05-22 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormaPagoGral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='FormaPagoSalud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ModalidadAtencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Planes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fdesde', models.DateField()),
                ('fhasta', models.DateField()),
                ('nombre', models.CharField(max_length=45)),
                ('estado', models.CharField(choices=[('0', 'Terminado'), ('1', 'Vigente')], max_length=1)),
                ('periodicidad', models.CharField(choices=[('0', 'Trimestral'), ('1', 'Semestral'), ('2', 'Anual')], max_length=1)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
            ],
            options={
                'db_table': 'tablas_planes',
                'ordering': ['fdesde', 'fhasta', 'nombre', 'estado', 'periodicidad', 'valor'],
            },
        ),
        migrations.CreateModel(
            name='Promociones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('fdesde', models.DateField()),
                ('fhasta', models.DateField()),
                ('pclave', models.CharField(max_length=45)),
                ('dcto_porcentaje', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dcto_cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('0', 'Terminada'), ('1', 'Vigente')], default='1', max_length=1)),
            ],
            options={
                'ordering': ['nombre', 'fdesde', 'fhasta', 'pclave', 'dcto_porcentaje', 'dcto_cantidad'],
            },
        ),
        migrations.CreateModel(
            name='Regiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('numero', models.CharField(max_length=4)),
            ],
            options={
                'ordering': ['nombre', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='Rubros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('areasalud', models.CharField(choices=[('0', 'No'), ('1', 'Si')], max_length=1)),
            ],
            options={
                'ordering': ['nombre', 'areasalud'],
            },
        ),
        migrations.CreateModel(
            name='TipoPrevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Comunas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablas.regiones')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Ciudades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablas.regiones')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('rubro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablas.rubros')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='SubCategorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablas.categorias')),
                ('rubro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablas.rubros')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
