# Generated by Django 5.0.3 on 2024-03-22 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormaPagoOtros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='FormaPagoSalud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ModalidadAtencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Promociones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('fdesde', models.DateField()),
                ('fhasta', models.DateField()),
                ('pclave', models.CharField(max_length=45)),
                ('dcto_porcentaje', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dcto_cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'ordering': ['nombre', 'fdesde', 'fhasta', 'pclave', 'dcto_porcentaje', 'dcto_cantidad'],
            },
        ),
        migrations.CreateModel(
            name='Regiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('numero', models.CharField(max_length=4)),
            ],
            options={
                'ordering': ['nombre', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='Rubros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('areasalud', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre', 'areasalud'],
            },
        ),
        migrations.CreateModel(
            name='TipoPrevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Comunas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablas.regiones')),
            ],
            options={
                'ordering': ['nombre', 'region'],
            },
        ),
        migrations.CreateModel(
            name='Ciudades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablas.regiones')),
            ],
            options={
                'ordering': ['nombre', 'region'],
            },
        ),
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('rubro', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='tablas.rubros')),
            ],
            options={
                'ordering': ['nombre', 'rubro'],
            },
        ),
        migrations.CreateModel(
            name='SubCategorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablas.categorias')),
                ('rubro', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='tablas.rubros')),
            ],
            options={
                'ordering': ['nombre', 'categoria', 'rubro'],
            },
        ),
    ]
