# Generated by Django 5.0.3 on 2024-03-27 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tablas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FormaPagoOtros',
            new_name='FormaPagoGral',
        ),
    ]
