# Generated by Django 5.0.3 on 2024-04-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablas', '0002_rename_formapagootros_formapagogral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubros',
            name='areasalud',
            field=models.PositiveSmallIntegerField(choices=[(0, 'No'), (1, 'Si')]),
        ),
    ]
