# Generated by Django 5.0.3 on 2024-04-02 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablas', '0004_alter_rubros_areasalud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubros',
            name='areasalud',
            field=models.CharField(choices=[('0', 'No'), ('1', 'Si')], max_length=1),
        ),
    ]
