# Generated by Django 5.0.3 on 2024-04-03 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablas', '0005_alter_rubros_areasalud'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorias',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='ciudades',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='comunas',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='subcategorias',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterField(
            model_name='categorias',
            name='rubro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablas.rubros'),
        ),
        migrations.AlterField(
            model_name='subcategorias',
            name='rubro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablas.rubros'),
        ),
    ]
