# Generated by Django 5.0.3 on 2024-05-13 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablas', '0006_alter_categorias_options_alter_ciudades_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fdesde', models.DateField()),
                ('fhasta', models.DateField()),
                ('nombre', models.CharField(max_length=45)),
                ('estado', models.CharField(choices=[('0', 'Terminado'), ('1', 'Vigente')], max_length=1)),
                ('periodicidad', models.CharField(choices=[('0', 'Trimestral'), ('1', 'Semestral'), ('2', 'Anual')], max_length=1)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
            ],
            options={
                'db_table': 'tablas_planes',
                'ordering': ['fdesde', 'fhasta', 'nombre', 'estado', 'periodicidad', 'valor'],
            },
        ),
    ]
