# Generated by Django 5.0.3 on 2024-05-14 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablas', '0007_planes'),
    ]

    operations = [
        migrations.AddField(
            model_name='promociones',
            name='estado',
            field=models.CharField(choices=[('0', 'Terminada'), ('1', 'Vigente')], default='1', max_length=1),
        ),
    ]
