# Generated by Django 5.0.7 on 2024-07-29 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banner', verbose_name='Imagen')),
                ('title', models.CharField(max_length=200)),
                ('cliente', models.CharField(max_length=20, verbose_name='RUT')),
                ('estado', models.CharField(max_length=20)),
                ('creacion', models.DateTimeField(auto_now=True, verbose_name='Fecha creacion')),
                ('modifica', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ['-creacion'],
            },
        ),
    ]
