# Generated by Django 5.0.7 on 2024-07-29 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0001_initial'),
        ('tablas', '0002_alter_planes_periodicidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='rubro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tablas.rubros'),
        ),
    ]
