# Generated by Django 5.0.7 on 2024-07-29 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0002_banner_rubro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Tipo')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Fecha creacion')),
                ('modifica', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
                'ordering': ['created'],
            },
        ),
        migrations.AddField(
            model_name='banner',
            name='categories',
            field=models.ManyToManyField(to='banner.category', verbose_name='Categoria'),
        ),
    ]
